export type ProductCategory = "Men" | "Women" | "Children" | "Perfume"

export type ProductBadge = "New" | "Best Seller" | "Premium" | "Limited Drop" | "Eco Packaged" | "AI Pick" | "Selling Fast" | "Sale"

export interface Product {
  id: string
  name: string
  slug: string
  brand: string
  category: ProductCategory
  subcategory: string
  description: string
  longDescription: string
  price: number
  compareAtPrice?: number
  currency: string
  images: string[]
  hoverImage?: string
  sizes: string[]
  colors: string[]
  material?: string
  fit?: string
  care?: string
  stock: number
  rating: number
  reviewCount: number
  badges: ProductBadge[]
  tags: string[]
  seoTitle: string
  seoDescription: string
  isFeatured: boolean
  isNewArrival: boolean
  isBestSeller: boolean
  collection?: string
  aiMatchScore?: number
  fragranceFamily?: string
  topNotes?: string[]
  heartNotes?: string[]
  baseNotes?: string[]
  longevity?: string
  projection?: string
  occasion?: string[]
  season?: string[]
  concentration?: string
  bottleSize?: string
  gender?: string
}

export interface Collection {
  id: string
  name: string
  slug: string
  description: string
  image: string
  productCount: number
}

export interface BlogPost {
  id: string
  title: string
  slug: string
  excerpt: string
  content: string
  category: string
  author: string
  publishDate: string
  image: string
  tags: string[]
  readTime: number
}

const S = "https://cdn.shopify.com/s/files/1/0660/8633/8733/files"

export const products: Product[] = [
  // ==================== MEN'S PRODUCTS ====================
  {
    id: "m001",
    name: "Navy Grindled Yarn Polo",
    slug: "navy-grindled-yarn-polo",
    brand: "Buy On Earth",
    category: "Men",
    subcategory: "Polos",
    description: "A textured grindled yarn polo in rich navy, perfect for smart-casual looks.",
    longDescription: "Elevate your polo game with this premium grindled yarn piece. The unique texture gives a sophisticated look while maintaining casual comfort. Features a ribbed collar, two-button placket, and side vents for ease of movement.",
    price: 899,
    compareAtPrice: 1299,
    currency: "INR",
    images: [`${S}/M11611B1_jpg.jpg`, `${S}/M11611B_jpg.jpg`],
    hoverImage: `${S}/M11611B_jpg.jpg`,
    sizes: ["S", "M", "L", "XL", "XXL"],
    colors: ["Navy"],
    material: "Cotton Blend Yarn",
    fit: "Regular",
    care: "Machine wash cold",
    stock: 120,
    rating: 4.6,
    reviewCount: 189,
    badges: ["New"],
    tags: ["polo", "navy", "textured"],
    seoTitle: "Navy Grindled Yarn Polo | Buy On Earth",
    seoDescription: "Premium grindled yarn polo in navy. Textured knit, ribbed collar.",
    isFeatured: true,
    isNewArrival: true,
    isBestSeller: false,
    collection: "earth-essentials",
    aiMatchScore: 91,
  },
  {
    id: "m002",
    name: "Woven Flannel Lounge Pants",
    slug: "woven-flannel-lounge-pants",
    brand: "Buy On Earth",
    category: "Men",
    subcategory: "Lounge Pants",
    description: "Ultra-soft woven flannel pants for lounging at home in style.",
    longDescription: "Crafted from brushed cotton flannel, these lounge pants offer unbeatable softness. Features an elastic waistband with drawstring, deep pockets, and a relaxed fit for maximum comfort.",
    price: 699,
    compareAtPrice: 999,
    currency: "INR",
    images: [`${S}/M10919V1.jpg`, `${S}/M10919V_jpg.jpg`],
    hoverImage: `${S}/M10919V_jpg.jpg`,
    sizes: ["S", "M", "L", "XL", "XXL"],
    colors: ["Charcoal"],
    material: "100% Cotton Flannel",
    fit: "Relaxed",
    care: "Machine wash warm",
    stock: 80,
    rating: 4.7,
    reviewCount: 156,
    badges: ["Best Seller"],
    tags: ["flannel", "lounge", "nightwear"],
    seoTitle: "Woven Flannel Lounge Pants | Buy On Earth",
    seoDescription: "Premium cotton flannel lounge pants. Ultra-soft, relaxed fit.",
    isFeatured: false,
    isNewArrival: false,
    isBestSeller: true,
    collection: "earth-essentials",
  },
  {
    id: "m003",
    name: "Printed Navy T-Shirt",
    slug: "printed-navy-tshirt",
    brand: "Buy On Earth",
    category: "Men",
    subcategory: "T-Shirts",
    description: "A classic printed tee in deep navy with a modern graphic detail.",
    longDescription: "This statement tee combines premium cotton comfort with a bold contemporary print. Pre-shrunk fabric ensures a consistent fit wash after wash. Crew neck, short sleeves, and a regular fit silhouette.",
    price: 599,
    compareAtPrice: 899,
    currency: "INR",
    images: [`${S}/M11591A1_jpg.jpg`, `${S}/M11591A_jpg.jpg`, `${S}/M11591A2_jpg.jpg`],
    hoverImage: `${S}/M11591A_jpg.jpg`,
    sizes: ["S", "M", "L", "XL", "XXL"],
    colors: ["Navy"],
    material: "100% Cotton",
    fit: "Regular",
    care: "Machine wash cold, inside out",
    stock: 200,
    rating: 4.5,
    reviewCount: 312,
    badges: ["Sale"],
    tags: ["t-shirt", "printed", "navy", "casual"],
    seoTitle: "Printed Navy T-Shirt | Buy On Earth",
    seoDescription: "Premium printed navy tee. 100% cotton, modern graphic.",
    isFeatured: true,
    isNewArrival: true,
    isBestSeller: true,
    collection: "earth-essentials",
    aiMatchScore: 88,
  },
  {
    id: "m004",
    name: "Textured Knit T-Shirt",
    slug: "textured-knit-tshirt",
    brand: "Buy On Earth",
    category: "Men",
    subcategory: "T-Shirts",
    description: "A richly textured knit tee for a sophisticated casual look.",
    longDescription: "Stand out from plain tees with this textured knit piece. The unique fabric creates depth and visual interest while maintaining a soft hand-feel. Perfect for layering or wearing alone.",
    price: 749,
    compareAtPrice: 1099,
    currency: "INR",
    images: [`${S}/M11596A1_jpg.jpg`, `${S}/M11596A_jpg.jpg`, `${S}/M11596A2_jpg.jpg`],
    hoverImage: `${S}/M11596A_jpg.jpg`,
    sizes: ["S", "M", "L", "XL"],
    colors: ["Black"],
    material: "Cotton Knit Blend",
    fit: "Regular",
    care: "Machine wash cold",
    stock: 90,
    rating: 4.7,
    reviewCount: 178,
    badges: ["Premium"],
    tags: ["textured", "knit", "premium"],
    seoTitle: "Textured Knit T-Shirt | Buy On Earth",
    seoDescription: "Premium textured knit tee. Sophisticated casual wear.",
    isFeatured: true,
    isNewArrival: false,
    isBestSeller: true,
    collection: "premium-edit",
  },
  {
    id: "m005",
    name: "Eyelet Knit Long Sleeve Tee",
    slug: "eyelet-knit-long-sleeve-tee",
    brand: "Buy On Earth",
    category: "Men",
    subcategory: "T-Shirts",
    description: "An open-weave eyelet knit tee with long sleeves for transitional weather.",
    longDescription: "This eyelet knit tee bridges the gap between casual and refined. The open-weave construction allows breathability while adding visual texture. Perfect for layering in cooler months or wearing on breezy evenings.",
    price: 999,
    compareAtPrice: 1499,
    currency: "INR",
    images: [`${S}/M11587A_2_jpg.jpg`, `${S}/M11587A_jpg.jpg`, `${S}/M11587A_1_jpg.jpg`],
    hoverImage: `${S}/M11587A_jpg.jpg`,
    sizes: ["S", "M", "L", "XL"],
    colors: ["Black"],
    material: "Cotton Eyelet Knit",
    fit: "Regular",
    care: "Hand wash recommended",
    stock: 60,
    rating: 4.8,
    reviewCount: 92,
    badges: ["Premium", "New"],
    tags: ["long sleeve", "eyelet", "knit", "premium"],
    seoTitle: "Eyelet Knit Long Sleeve Tee | Buy On Earth",
    seoDescription: "Premium eyelet knit long sleeve tee. Open-weave, breathable.",
    isFeatured: true,
    isNewArrival: true,
    isBestSeller: false,
    collection: "premium-edit",
    aiMatchScore: 94,
  },
  {
    id: "m006",
    name: "French Terry Oversized Tee",
    slug: "french-terry-oversized-tee",
    brand: "Buy On Earth",
    category: "Men",
    subcategory: "T-Shirts",
    description: "A heavyweight French terry oversized tee for the streetwear-savvy.",
    longDescription: "Premium French terry fabric gives this oversized tee a structured yet comfortable feel. Dropped shoulders, extended body length, and ribbed cuffs create a modern streetwear silhouette.",
    price: 799,
    compareAtPrice: 1199,
    currency: "INR",
    images: [`${S}/M11467D1_ff24cce6-bd14-42ef-b0e3-e0273bb83770.jpg`, `${S}/M11467D1_abed70a3-b49b-4334-8836-6864d3e9a191.jpg`],
    hoverImage: `${S}/M11467D1_abed70a3-b49b-4334-8836-6864d3e9a191.jpg`,
    sizes: ["S", "M", "L", "XL", "XXL"],
    colors: ["Black", "Charcoal"],
    material: "French Terry Cotton",
    fit: "Oversized",
    care: "Machine wash cold",
    stock: 140,
    rating: 4.6,
    reviewCount: 267,
    badges: ["Best Seller", "AI Pick"],
    tags: ["oversized", "french terry", "streetwear"],
    seoTitle: "French Terry Oversized Tee | Buy On Earth",
    seoDescription: "Heavyweight French terry oversized tee. Streetwear essential.",
    isFeatured: false,
    isNewArrival: false,
    isBestSeller: true,
    collection: "earth-essentials",
    aiMatchScore: 96,
  },
  {
    id: "m007",
    name: "Printed Olive T-Shirt",
    slug: "printed-olive-tshirt",
    brand: "Buy On Earth",
    category: "Men",
    subcategory: "T-Shirts",
    description: "A bold printed tee in earthy olive tones.",
    longDescription: "This olive tee features a distinctive print that adds character to any casual outfit. Premium cotton construction ensures comfort and durability.",
    price: 649,
    currency: "INR",
    images: [`${S}/M11603B1_jpg.jpg`, `${S}/M11603B_jpg.jpg`],
    hoverImage: `${S}/M11603B_jpg.jpg`,
    sizes: ["S", "M", "L", "XL"],
    colors: ["Olive"],
    material: "100% Cotton",
    fit: "Regular",
    care: "Machine wash cold",
    stock: 110,
    rating: 4.4,
    reviewCount: 98,
    badges: ["New"],
    tags: ["olive", "printed", "casual"],
    seoTitle: "Printed Olive T-Shirt | Buy On Earth",
    seoDescription: "Printed olive tee. Premium cotton, bold graphic.",
    isFeatured: false,
    isNewArrival: true,
    isBestSeller: false,
  },
  {
    id: "m008",
    name: "French Terry Olive Oversized Tee",
    slug: "french-terry-olive-oversized",
    brand: "Buy On Earth",
    category: "Men",
    subcategory: "T-Shirts",
    description: "Heavyweight French terry oversized tee in a trendy olive shade.",
    longDescription: "The same beloved French terry construction in a rich olive colorway. Dropped shoulders, heavyweight feel, and a modern oversized silhouette that pairs perfectly with joggers or denim.",
    price: 799,
    currency: "INR",
    images: [`${S}/M11597G1_jpg.jpg`, `${S}/M11597G_jpg.jpg`],
    hoverImage: `${S}/M11597G_jpg.jpg`,
    sizes: ["S", "M", "L", "XL"],
    colors: ["Olive"],
    material: "French Terry Cotton",
    fit: "Oversized",
    care: "Machine wash cold",
    stock: 75,
    rating: 4.7,
    reviewCount: 134,
    badges: ["Selling Fast"],
    tags: ["olive", "oversized", "french terry"],
    seoTitle: "French Terry Olive Oversized Tee | Buy On Earth",
    seoDescription: "Heavyweight olive oversized tee in premium French terry.",
    isFeatured: false,
    isNewArrival: false,
    isBestSeller: true,
  },
  {
    id: "m009",
    name: "Dark Heather Jogger",
    slug: "dark-heather-jogger",
    brand: "Buy On Earth",
    category: "Men",
    subcategory: "Joggers",
    description: "Premium heavyweight jogger in dark heather for athletic and casual wear.",
    longDescription: "Built for comfort and style, these heavyweight joggers feature a brushed interior, elastic waistband with drawstring, ribbed cuffs, and deep zip pockets. The dark heather fabric adds sophistication to athleisure.",
    price: 1099,
    compareAtPrice: 1499,
    currency: "INR",
    images: [`${S}/M11557A1_jpg.jpg`, `${S}/M11557A_jpg.jpg`],
    hoverImage: `${S}/M11557A_jpg.jpg`,
    sizes: ["S", "M", "L", "XL", "XXL"],
    colors: ["Dark Heather"],
    material: "Heavy GSM Cotton Blend",
    fit: "Tapered",
    care: "Machine wash cold",
    stock: 100,
    rating: 4.8,
    reviewCount: 287,
    badges: ["Best Seller", "Premium"],
    tags: ["jogger", "athleisure", "heavyweight"],
    seoTitle: "Dark Heather Jogger | Buy On Earth",
    seoDescription: "Premium heavyweight jogger. Brushed interior, tapered fit.",
    isFeatured: true,
    isNewArrival: false,
    isBestSeller: true,
    collection: "premium-edit",
    aiMatchScore: 92,
  },
  {
    id: "m010",
    name: "Navy Melange Track Pant",
    slug: "navy-melange-track-pant",
    brand: "Buy On Earth",
    category: "Men",
    subcategory: "Joggers",
    description: "A French terry track pant in navy melange for everyday comfort.",
    longDescription: "Our core track pant in premium French terry fabric. The navy melange creates visual texture while the brushed interior provides all-day comfort. Elasticated waist, drawstring, and cuffed ankles.",
    price: 1199,
    currency: "INR",
    images: [`${S}/M11300C_1copy.jpg`, `${S}/M11300C.jpg`, `${S}/M11300C_2.jpg`],
    hoverImage: `${S}/M11300C.jpg`,
    sizes: ["S", "M", "L", "XL", "XXL"],
    colors: ["Navy Melange"],
    material: "French Terry Cotton",
    fit: "Regular",
    care: "Machine wash cold",
    stock: 95,
    rating: 4.6,
    reviewCount: 201,
    badges: ["Premium"],
    tags: ["track pant", "french terry", "navy"],
    seoTitle: "Navy Melange Track Pant | Buy On Earth",
    seoDescription: "Premium French terry track pant in navy melange.",
    isFeatured: false,
    isNewArrival: false,
    isBestSeller: false,
    collection: "earth-essentials",
  },
  {
    id: "m011",
    name: "Beach Outfit Blue Shirt",
    slug: "beach-outfit-blue-shirt",
    brand: "Buy On Earth",
    category: "Men",
    subcategory: "Shirts",
    description: "A breezy vacation-ready shirt in ocean blue tones.",
    longDescription: "Channel resort vibes with this relaxed beach shirt. Lightweight fabric, camp collar, and a vibrant blue print make this perfect for holidays, brunches, and weekend getaways.",
    price: 1499,
    compareAtPrice: 1999,
    currency: "INR",
    images: [`${S}/M11553Bs1.jpg`, `${S}/M11553B_2.jpg_1.jpg`, `${S}/M11553B_1.jpg_1.jpg`, `${S}/M11553B.jpg_1.jpg`],
    hoverImage: `${S}/M11553B_2.jpg_1.jpg`,
    sizes: ["S", "M", "L", "XL"],
    colors: ["Blue"],
    material: "Lightweight Cotton",
    fit: "Relaxed",
    care: "Machine wash cold",
    stock: 50,
    rating: 4.5,
    reviewCount: 76,
    badges: ["New", "Premium"],
    tags: ["beach", "shirt", "vacation", "blue"],
    seoTitle: "Beach Outfit Blue Shirt | Buy On Earth",
    seoDescription: "Breezy vacation-ready shirt in ocean blue. Camp collar.",
    isFeatured: true,
    isNewArrival: true,
    isBestSeller: false,
    collection: "summer-resort",
    aiMatchScore: 87,
  },
  {
    id: "m012",
    name: "Printed Woven Shirt",
    slug: "printed-woven-shirt",
    brand: "Buy On Earth",
    category: "Men",
    subcategory: "Shirts",
    description: "A refined printed woven shirt for smart-casual occasions.",
    longDescription: "This woven shirt features an all-over print on premium fabric. Sharp collar, button-through front, and a tailored fit make it ideal for dates, dinners, and office casual days.",
    price: 1499,
    currency: "INR",
    images: [`${S}/M11552A1_jpg.jpg`, `${S}/M11552A.jpg`],
    hoverImage: `${S}/M11552A.jpg`,
    sizes: ["S", "M", "L", "XL"],
    colors: ["Black"],
    material: "Woven Cotton",
    fit: "Slim",
    care: "Machine wash cold",
    stock: 65,
    rating: 4.6,
    reviewCount: 112,
    badges: ["Premium"],
    tags: ["woven", "printed", "shirt", "smart casual"],
    seoTitle: "Printed Woven Shirt | Buy On Earth",
    seoDescription: "Refined printed woven shirt. Smart-casual essential.",
    isFeatured: false,
    isNewArrival: false,
    isBestSeller: false,
    collection: "premium-edit",
  },
  {
    id: "m013",
    name: "Woven Denim Shirt",
    slug: "woven-denim-shirt",
    brand: "Buy On Earth",
    category: "Men",
    subcategory: "Shirts",
    description: "A classic denim shirt crafted from woven fabric with a lived-in feel.",
    longDescription: "The timeless denim shirt reimagined. Premium woven denim fabric, snap buttons, dual chest pockets, and a slightly relaxed fit. Versatile enough for layering or wearing alone.",
    price: 1699,
    compareAtPrice: 2199,
    currency: "INR",
    images: [`${S}/M11554A1_jpg.jpg`, `${S}/M11554A.jpg`],
    hoverImage: `${S}/M11554A.jpg`,
    sizes: ["S", "M", "L", "XL", "XXL"],
    colors: ["Denim Blue"],
    material: "Woven Denim",
    fit: "Regular",
    care: "Machine wash cold, inside out",
    stock: 70,
    rating: 4.7,
    reviewCount: 145,
    badges: ["Best Seller"],
    tags: ["denim", "shirt", "classic"],
    seoTitle: "Woven Denim Shirt | Buy On Earth",
    seoDescription: "Classic woven denim shirt. Premium fabric, snap buttons.",
    isFeatured: false,
    isNewArrival: false,
    isBestSeller: true,
  },
  {
    id: "m014",
    name: "Navy Melange French Terry Shorts",
    slug: "navy-melange-french-terry-shorts",
    brand: "Buy On Earth",
    category: "Men",
    subcategory: "Shorts",
    description: "Comfortable French terry shorts in navy melange for lounging and errands.",
    longDescription: "These French terry shorts pair perfectly with our track pants for a complete athleisure look. Elastic waistband, drawstring, and side pockets in a mid-thigh length.",
    price: 799,
    currency: "INR",
    images: [`${S}/M11542D.jpg`, `${S}/M11542D2.jpg`, `${S}/M11542D3.jpg`],
    hoverImage: `${S}/M11542D2.jpg`,
    sizes: ["S", "M", "L", "XL"],
    colors: ["Navy Melange"],
    material: "French Terry Cotton",
    fit: "Regular",
    care: "Machine wash cold",
    stock: 85,
    rating: 4.5,
    reviewCount: 134,
    badges: ["Sale"],
    tags: ["shorts", "french terry", "lounge"],
    seoTitle: "Navy Melange French Terry Shorts | Buy On Earth",
    seoDescription: "Comfortable French terry shorts in navy melange.",
    isFeatured: false,
    isNewArrival: false,
    isBestSeller: false,
    collection: "earth-essentials",
  },
  {
    id: "m015",
    name: "Mario Print T-Shirt",
    slug: "mario-print-tshirt",
    brand: "Buy On Earth",
    category: "Men",
    subcategory: "T-Shirts",
    description: "A fun pop-culture tee featuring a bold Mario-inspired graphic.",
    longDescription: "Level up your casual game with this pop-culture graphic tee. Premium cotton, vibrant print that won't fade, and a comfortable regular fit.",
    price: 849,
    currency: "INR",
    images: [`${S}/Gemini_Generated_Image_o0ersdo0ersdo0ercopy.jpg`, `${S}/M11184A_jpg.jpg`],
    hoverImage: `${S}/M11184A_jpg.jpg`,
    sizes: ["S", "M", "L", "XL"],
    colors: ["Black"],
    material: "100% Cotton",
    fit: "Regular",
    care: "Machine wash cold, inside out",
    stock: 120,
    rating: 4.4,
    reviewCount: 198,
    badges: ["Selling Fast"],
    tags: ["graphic", "pop culture", "printed"],
    seoTitle: "Mario Print T-Shirt | Buy On Earth",
    seoDescription: "Pop-culture graphic tee. Premium cotton, vibrant print.",
    isFeatured: false,
    isNewArrival: false,
    isBestSeller: true,
  },
  {
    id: "m016",
    name: "Navy Knit Shorts",
    slug: "navy-knit-shorts",
    brand: "Buy On Earth",
    category: "Men",
    subcategory: "Shorts",
    description: "Lightweight French terry knit shorts in navy for active days.",
    longDescription: "These knit shorts are your go-to for gym sessions, errands, or lazy weekends. French terry fabric, elastic waistband, and a clean tapered silhouette.",
    price: 749,
    currency: "INR",
    images: [`${S}/M11499B2.jpg`, `${S}/M11499B_jpg.jpg`, `${S}/M11499B1.jpg`],
    hoverImage: `${S}/M11499B_jpg.jpg`,
    sizes: ["S", "M", "L", "XL"],
    colors: ["Navy"],
    material: "French Terry Knit",
    fit: "Regular",
    care: "Machine wash cold",
    stock: 90,
    rating: 4.5,
    reviewCount: 112,
    badges: [],
    tags: ["shorts", "knit", "navy", "athleisure"],
    seoTitle: "Navy Knit Shorts | Buy On Earth",
    seoDescription: "Lightweight French terry knit shorts. Perfect for active days.",
    isFeatured: false,
    isNewArrival: false,
    isBestSeller: false,
  },

  // ==================== WOMEN'S PRODUCTS ====================
  {
    id: "w001",
    name: "Black Active Wear Shorts",
    slug: "black-active-wear-shorts",
    brand: "Buy On Earth",
    category: "Women",
    subcategory: "Shorts",
    description: "Lightweight active wear shorts for workouts and everyday wear.",
    longDescription: "These active wear shorts feature moisture-wicking fabric, a comfortable elastic waistband, and a flattering mid-thigh length. Perfect for gym, yoga, or casual outings.",
    price: 499,
    currency: "INR",
    images: [`${S}/W13493A1_jpg.jpg`],
    sizes: ["XS", "S", "M", "L", "XL"],
    colors: ["Black"],
    material: "Polyester Blend",
    fit: "Regular",
    care: "Machine wash cold",
    stock: 150,
    rating: 4.5,
    reviewCount: 210,
    badges: ["Best Seller"],
    tags: ["active wear", "shorts", "gym"],
    seoTitle: "Black Active Wear Shorts | Buy On Earth",
    seoDescription: "Lightweight active wear shorts for workouts.",
    isFeatured: false,
    isNewArrival: false,
    isBestSeller: true,
  },
  {
    id: "w002",
    name: "Viscose Embroidery Tank",
    slug: "viscose-embroidery-tank",
    brand: "Buy On Earth",
    category: "Women",
    subcategory: "Tops",
    description: "A delicate viscose tank with elegant embroidery detail.",
    longDescription: "This viscose tank features intricate embroidery work that adds a touch of artisanal charm. The soft drape and breathable fabric make it perfect for warm days.",
    price: 499,
    compareAtPrice: 799,
    currency: "INR",
    images: [`${S}/ChatGPTImageApr28_2026_01_02_29PMcopy_jpg.jpg`],
    sizes: ["XS", "S", "M", "L"],
    colors: ["White"],
    material: "Viscose",
    fit: "Regular",
    care: "Hand wash",
    stock: 80,
    rating: 4.6,
    reviewCount: 134,
    badges: ["Sale"],
    tags: ["tank", "embroidery", "viscose"],
    seoTitle: "Viscose Embroidery Tank | Buy On Earth",
    seoDescription: "Delicate viscose tank with embroidery detail.",
    isFeatured: false,
    isNewArrival: true,
    isBestSeller: false,
  },
  {
    id: "w003",
    name: "Printed Casual Top",
    slug: "printed-casual-top",
    brand: "Buy On Earth",
    category: "Women",
    subcategory: "Tops",
    description: "A breezy printed top for effortless everyday style.",
    longDescription: "This casual top features a beautiful all-over print on lightweight fabric. Relaxed fit, short sleeves, and a flattering neckline make it a wardrobe staple.",
    price: 599,
    currency: "INR",
    images: [`${S}/W13499A1_jpg.jpg`],
    sizes: ["XS", "S", "M", "L", "XL"],
    colors: ["Multi"],
    material: "Cotton Blend",
    fit: "Relaxed",
    care: "Machine wash cold",
    stock: 120,
    rating: 4.4,
    reviewCount: 167,
    badges: ["New"],
    tags: ["printed", "casual", "top"],
    seoTitle: "Printed Casual Top | Buy On Earth",
    seoDescription: "Breezy printed top for everyday style.",
    isFeatured: true,
    isNewArrival: true,
    isBestSeller: false,
    aiMatchScore: 85,
  },
  {
    id: "w004",
    name: "Magyar Sleeve Embroidery Top",
    slug: "magyar-sleeve-embroidery-top",
    brand: "Buy On Earth",
    category: "Women",
    subcategory: "Tops",
    description: "An ethnic-inspired top with magyar sleeves and beautiful embroidery.",
    longDescription: "This elegant top features traditional embroidery on a modern silhouette. Magyar sleeves create a flattering shape while the embroidery adds artisanal charm. Perfect for festivals and special occasions.",
    price: 649,
    compareAtPrice: 999,
    currency: "INR",
    images: [`${S}/W13477A1copy.jpg`],
    sizes: ["S", "M", "L", "XL"],
    colors: ["White"],
    material: "Cotton",
    fit: "Regular",
    care: "Hand wash",
    stock: 60,
    rating: 4.7,
    reviewCount: 89,
    badges: ["Premium"],
    tags: ["embroidery", "ethnic", "magyar sleeve"],
    seoTitle: "Magyar Sleeve Embroidery Top | Buy On Earth",
    seoDescription: "Ethnic-inspired embroidery top with magyar sleeves.",
    isFeatured: true,
    isNewArrival: true,
    isBestSeller: false,
    collection: "premium-edit",
    aiMatchScore: 90,
  },
  {
    id: "w005",
    name: "Printed Viscose Short Set",
    slug: "printed-viscose-short-set",
    brand: "Buy On Earth",
    category: "Women",
    subcategory: "Nightwear",
    description: "A printed viscose short set for comfortable nights and lazy mornings.",
    longDescription: "This matching short set features a relaxed top and comfortable shorts in soft printed viscose. Breathable fabric keeps you cool through the night.",
    price: 899,
    compareAtPrice: 1299,
    currency: "INR",
    images: [`${S}/W13500Aabc1_jpg.jpg`],
    sizes: ["S", "M", "L", "XL"],
    colors: ["Multi"],
    material: "Viscose",
    fit: "Relaxed",
    care: "Machine wash cold",
    stock: 90,
    rating: 4.6,
    reviewCount: 156,
    badges: ["Best Seller", "AI Pick"],
    tags: ["nightwear", "short set", "viscose", "printed"],
    seoTitle: "Printed Viscose Short Set | Buy On Earth",
    seoDescription: "Comfortable printed viscose short set for lounging.",
    isFeatured: false,
    isNewArrival: false,
    isBestSeller: true,
    aiMatchScore: 93,
  },
  {
    id: "w006",
    name: "Woven Checked Skirt",
    slug: "woven-checked-skirt",
    brand: "Buy On Earth",
    category: "Women",
    subcategory: "Skirts",
    description: "A classic checked skirt in woven fabric for a polished look.",
    longDescription: "This woven checked skirt brings a touch of preppy sophistication. A-line silhouette, lined interior, and a concealed zip closure. Pairs beautifully with blouses and boots.",
    price: 1499,
    currency: "INR",
    images: [`${S}/W13488A1_jpg.jpg`],
    sizes: ["XS", "S", "M", "L"],
    colors: ["Multi"],
    material: "Woven Cotton Blend",
    fit: "A-Line",
    care: "Dry clean recommended",
    stock: 40,
    rating: 4.8,
    reviewCount: 67,
    badges: ["Premium", "New"],
    tags: ["checked", "skirt", "woven", "classic"],
    seoTitle: "Woven Checked Skirt | Buy On Earth",
    seoDescription: "Classic woven checked skirt. A-line, premium fabric.",
    isFeatured: true,
    isNewArrival: true,
    isBestSeller: false,
    collection: "premium-edit",
  },
  {
    id: "w007",
    name: "Gypsy Neck Olive Top",
    slug: "gypsy-neck-olive-top",
    brand: "Buy On Earth",
    category: "Women",
    subcategory: "Tops",
    description: "A bohemian gypsy-neck top in rich olive with gathered detailing.",
    longDescription: "This olive top features a romantic gypsy neckline with elastic gathering. Flowy silhouette, soft fabric, and earthy tones make it perfect for boho-chic styling.",
    price: 1199,
    compareAtPrice: 1599,
    currency: "INR",
    images: [`${S}/W13445A1_jpg.jpg`],
    sizes: ["S", "M", "L", "XL"],
    colors: ["Olive"],
    material: "Viscose Cotton",
    fit: "Relaxed",
    care: "Machine wash cold",
    stock: 55,
    rating: 4.5,
    reviewCount: 98,
    badges: ["Premium"],
    tags: ["gypsy neck", "olive", "bohemian"],
    seoTitle: "Gypsy Neck Olive Top | Buy On Earth",
    seoDescription: "Bohemian gypsy-neck top in olive. Gathered detailing.",
    isFeatured: false,
    isNewArrival: false,
    isBestSeller: false,
    collection: "premium-edit",
  },
  {
    id: "w008",
    name: "Lace Button-Down Shirt",
    slug: "lace-button-down-shirt",
    brand: "Buy On Earth",
    category: "Women",
    subcategory: "Shirts",
    description: "A feminine lace-detailed button-down shirt for elegant occasions.",
    longDescription: "This button-down shirt features delicate lace panels that add femininity to a classic silhouette. Pearl buttons, pointed collar, and a tailored fit.",
    price: 1499,
    currency: "INR",
    images: [`${S}/W13485A3.jpg`],
    sizes: ["XS", "S", "M", "L"],
    colors: ["White"],
    material: "Cotton Lace Blend",
    fit: "Slim",
    care: "Hand wash",
    stock: 45,
    rating: 4.8,
    reviewCount: 72,
    badges: ["Premium", "Limited Drop"],
    tags: ["lace", "button-down", "elegant"],
    seoTitle: "Lace Button-Down Shirt | Buy On Earth",
    seoDescription: "Feminine lace button-down shirt. Pearl buttons, elegant.",
    isFeatured: true,
    isNewArrival: true,
    isBestSeller: false,
    collection: "premium-edit",
    aiMatchScore: 89,
  },
  {
    id: "w009",
    name: "Woven Black Short Dress",
    slug: "woven-black-short-dress",
    brand: "Buy On Earth",
    category: "Women",
    subcategory: "Dresses",
    description: "A chic little black dress in premium woven fabric.",
    longDescription: "Every woman needs a perfect LBD. This woven black dress features clean lines, a flattering fit-and-flare silhouette, and premium fabric that drapes beautifully.",
    price: 1799,
    compareAtPrice: 2499,
    currency: "INR",
    images: [`${S}/W13486A1_jpg.jpg`],
    sizes: ["XS", "S", "M", "L"],
    colors: ["Black"],
    material: "Woven Polyester Blend",
    fit: "Fit & Flare",
    care: "Dry clean",
    stock: 35,
    rating: 4.9,
    reviewCount: 56,
    badges: ["Premium", "Best Seller"],
    tags: ["LBD", "black dress", "woven", "party"],
    seoTitle: "Woven Black Short Dress | Buy On Earth",
    seoDescription: "Chic little black dress. Premium woven fabric, fit-and-flare.",
    isFeatured: true,
    isNewArrival: false,
    isBestSeller: true,
    collection: "premium-edit",
    aiMatchScore: 95,
  },

  // ==================== CHILDREN'S PRODUCTS ====================
  {
    id: "k001",
    name: "Girls Stretch Knit Shorts",
    slug: "girls-stretch-knit-shorts",
    brand: "Buy On Earth",
    category: "Children",
    subcategory: "Shorts",
    description: "Comfortable stretch knit shorts for active little ones.",
    longDescription: "These stretch knit shorts are perfect for active kids. Soft, stretchy fabric moves with them, while the elastic waistband ensures easy dressing. Available in fun colors.",
    price: 349,
    currency: "INR",
    images: [`${S}/G21992A_jpg.jpg`],
    sizes: ["2-3Y", "4-5Y", "6-7Y", "8-9Y"],
    colors: ["Pink", "Blue"],
    material: "Cotton Stretch Knit",
    fit: "Regular",
    care: "Machine wash warm",
    stock: 200,
    rating: 4.6,
    reviewCount: 234,
    badges: ["Best Seller"],
    tags: ["girls", "shorts", "stretch", "active"],
    seoTitle: "Girls Stretch Knit Shorts | Buy On Earth",
    seoDescription: "Comfortable stretch knit shorts for girls.",
    isFeatured: false,
    isNewArrival: false,
    isBestSeller: true,
  },
  {
    id: "k002",
    name: "Girls Printed Night Dress",
    slug: "girls-printed-night-dress",
    brand: "Buy On Earth",
    category: "Children",
    subcategory: "Nightwear",
    description: "A soft printed night dress for sweet dreams and cozy nights.",
    longDescription: "This adorable night dress features playful prints on super-soft cotton. The relaxed fit and breathable fabric ensure comfortable sleep all night long.",
    price: 549,
    currency: "INR",
    images: [`${S}/G22179A1.jpg`],
    sizes: ["2-3Y", "4-5Y", "6-7Y", "8-9Y", "10-11Y"],
    colors: ["Multi"],
    material: "100% Cotton",
    fit: "Relaxed",
    care: "Machine wash warm",
    stock: 120,
    rating: 4.7,
    reviewCount: 167,
    badges: ["New"],
    tags: ["nightwear", "night dress", "girls"],
    seoTitle: "Girls Printed Night Dress | Buy On Earth",
    seoDescription: "Soft printed night dress for girls. 100% cotton.",
    isFeatured: true,
    isNewArrival: true,
    isBestSeller: false,
    aiMatchScore: 86,
  },
  {
    id: "k003",
    name: "Girls Printed Dress",
    slug: "girls-printed-dress",
    brand: "Buy On Earth",
    category: "Children",
    subcategory: "Dresses",
    description: "A charming printed dress for everyday wear and special occasions.",
    longDescription: "This versatile printed dress is perfect for school, parties, or weekend outings. Vibrant prints, comfortable fit, and easy-care fabric make it a parent favorite.",
    price: 699,
    currency: "INR",
    images: [`${S}/G22172A1.jpg`],
    sizes: ["2-3Y", "4-5Y", "6-7Y", "8-9Y"],
    colors: ["Multi"],
    material: "Cotton Blend",
    fit: "Regular",
    care: "Machine wash cold",
    stock: 100,
    rating: 4.5,
    reviewCount: 189,
    badges: ["New", "AI Pick"],
    tags: ["girls", "dress", "printed", "party"],
    seoTitle: "Girls Printed Dress | Buy On Earth",
    seoDescription: "Charming printed dress for girls. Vibrant, comfortable.",
    isFeatured: true,
    isNewArrival: true,
    isBestSeller: false,
    aiMatchScore: 88,
  },
  {
    id: "k004",
    name: "Boys Printed Grey T-Shirt",
    slug: "boys-printed-grey-tshirt",
    brand: "Buy On Earth",
    category: "Children",
    subcategory: "T-Shirts",
    description: "A cool printed tee in grey for boys who love to stand out.",
    longDescription: "This grey tee features a fun graphic print that boys love. Premium cotton, pre-shrunk, and built to withstand active play.",
    price: 549,
    currency: "INR",
    images: [`${S}/K22168B1.jpg`],
    sizes: ["4-5Y", "6-7Y", "8-9Y", "10-11Y", "12-13Y"],
    colors: ["Grey"],
    material: "100% Cotton",
    fit: "Regular",
    care: "Machine wash cold",
    stock: 150,
    rating: 4.4,
    reviewCount: 156,
    badges: ["Selling Fast"],
    tags: ["boys", "t-shirt", "printed", "grey"],
    seoTitle: "Boys Printed Grey T-Shirt | Buy On Earth",
    seoDescription: "Cool printed grey tee for boys. 100% cotton.",
    isFeatured: false,
    isNewArrival: true,
    isBestSeller: false,
  },
  {
    id: "k005",
    name: "Girls Printed Shorty Sets",
    slug: "girls-printed-shorty-sets",
    brand: "Buy On Earth",
    category: "Children",
    subcategory: "Sets",
    description: "A matching printed top and shorts set for playful summer days.",
    longDescription: "This coordinated set includes a printed top and matching shorts in soft cotton. Easy to dress, comfortable to wear, and adorable to look at.",
    price: 649,
    compareAtPrice: 899,
    currency: "INR",
    images: [`${S}/G22169Aabc_jpg.jpg`],
    sizes: ["2-3Y", "4-5Y", "6-7Y", "8-9Y"],
    colors: ["Multi"],
    material: "100% Cotton",
    fit: "Regular",
    care: "Machine wash warm",
    stock: 80,
    rating: 4.7,
    reviewCount: 134,
    badges: ["Sale", "Eco Packaged"],
    tags: ["girls", "shorty set", "summer", "matching"],
    seoTitle: "Girls Printed Shorty Sets | Buy On Earth",
    seoDescription: "Matching printed top and shorts set for girls.",
    isFeatured: false,
    isNewArrival: false,
    isBestSeller: true,
  },
  {
    id: "k006",
    name: "Girls Printed Pyjama Sets",
    slug: "girls-printed-pyjama-sets",
    brand: "Buy On Earth",
    category: "Children",
    subcategory: "Nightwear",
    description: "Cozy printed pyjama sets for bedtime comfort.",
    longDescription: "These matching pyjama sets feature playful prints on super-soft cotton. Long sleeve top and full-length pants keep little ones warm and comfortable all night.",
    price: 799,
    currency: "INR",
    images: [`${S}/G22168Aabc_jpg.jpg`],
    sizes: ["2-3Y", "4-5Y", "6-7Y", "8-9Y", "10-11Y"],
    colors: ["Multi"],
    material: "100% Cotton",
    fit: "Regular",
    care: "Machine wash warm",
    stock: 100,
    rating: 4.8,
    reviewCount: 201,
    badges: ["Best Seller"],
    tags: ["pyjama", "nightwear", "girls", "sleepwear"],
    seoTitle: "Girls Printed Pyjama Sets | Buy On Earth",
    seoDescription: "Cozy printed pyjama sets for girls. 100% cotton.",
    isFeatured: false,
    isNewArrival: false,
    isBestSeller: true,
  },
  {
    id: "k007",
    name: "Girls Glitter Printed Top",
    slug: "girls-glitter-printed-top",
    brand: "Buy On Earth",
    category: "Children",
    subcategory: "Tops",
    description: "A sparkly glitter print top for girls who love to shine.",
    longDescription: "This white cotton top features a beautiful glitter print that catches the light. Perfect for parties, playdates, and photo ops.",
    price: 549,
    currency: "INR",
    images: [`${S}/G22060A.jpg`],
    sizes: ["2-3Y", "4-5Y", "6-7Y", "8-9Y"],
    colors: ["White"],
    material: "100% Cotton",
    fit: "Regular",
    care: "Machine wash cold, inside out",
    stock: 90,
    rating: 4.5,
    reviewCount: 112,
    badges: ["New"],
    tags: ["glitter", "party", "girls", "top"],
    seoTitle: "Girls Glitter Printed Top | Buy On Earth",
    seoDescription: "Sparkly glitter print top for girls. 100% cotton.",
    isFeatured: true,
    isNewArrival: true,
    isBestSeller: false,
    aiMatchScore: 82,
  },

  // ==================== PERFUME PRODUCTS ====================
  {
    id: "p001",
    name: "Earth Noir Eau De Parfum",
    slug: "earth-noir-edp",
    brand: "Buy On Earth",
    category: "Perfume",
    subcategory: "Eau De Parfum",
    description: "A bold, mysterious fragrance with deep woody-amber notes for evening wear.",
    longDescription: "Earth Noir is our signature evening fragrance, crafted for those who command attention. Opening with vibrant bergamot and pink pepper, it evolves into a rich heart of saffron and rose before settling into a base of oud, amber, and sandalwood.",
    price: 3999,
    compareAtPrice: 5499,
    currency: "INR",
    images: ["https://images.unsplash.com/photo-1541643600914-78b084683702?w=600&q=80", "https://images.unsplash.com/photo-1587017539504-67cfbddac569?w=600&q=80"],
    hoverImage: "https://images.unsplash.com/photo-1587017539504-67cfbddac569?w=600&q=80",
    sizes: [],
    colors: [],
    stock: 60,
    rating: 4.9,
    reviewCount: 345,
    badges: ["Premium", "Best Seller"],
    tags: ["perfume", "oud", "evening", "woody"],
    seoTitle: "Earth Noir EDP | Buy On Earth",
    seoDescription: "Signature evening fragrance. Oud, amber, sandalwood.",
    isFeatured: true,
    isNewArrival: false,
    isBestSeller: true,
    collection: "signature-scents",
    aiMatchScore: 97,
    fragranceFamily: "Woody Amber",
    topNotes: ["Bergamot", "Pink Pepper", "Citrus"],
    heartNotes: ["Saffron", "Rose", "Lavender"],
    baseNotes: ["Oud", "Amber", "Sandalwood", "Musk"],
    longevity: "8-10 hours",
    projection: "Strong",
    occasion: ["Evening", "Date Night", "Special Events"],
    season: ["Fall", "Winter"],
    concentration: "Eau De Parfum",
    bottleSize: "100ml",
    gender: "Unisex",
  },
  {
    id: "p002",
    name: "Terra Bloom Eau De Toilette",
    slug: "terra-bloom-edt",
    brand: "Buy On Earth",
    category: "Perfume",
    subcategory: "Eau De Toilette",
    description: "A fresh, floral daytime fragrance inspired by blooming meadows.",
    longDescription: "Terra Bloom captures the essence of a sunlit garden. Bright citrus and green tea open to a heart of jasmine, peony, and lily of the valley, finished with white musk and cedarwood.",
    price: 2499,
    compareAtPrice: 3499,
    currency: "INR",
    images: ["https://images.unsplash.com/photo-1588405748880-12d1d2a59f75?w=600&q=80", "https://images.unsplash.com/photo-1592945403244-b3fbafd7f539?w=600&q=80"],
    hoverImage: "https://images.unsplash.com/photo-1592945403244-b3fbafd7f539?w=600&q=80",
    sizes: [],
    colors: [],
    stock: 80,
    rating: 4.7,
    reviewCount: 198,
    badges: ["New", "AI Pick"],
    tags: ["perfume", "floral", "daytime", "fresh"],
    seoTitle: "Terra Bloom EDT | Buy On Earth",
    seoDescription: "Fresh floral daytime fragrance. Jasmine, peony, cedarwood.",
    isFeatured: true,
    isNewArrival: true,
    isBestSeller: false,
    collection: "signature-scents",
    aiMatchScore: 91,
    fragranceFamily: "Floral Fresh",
    topNotes: ["Lemon", "Green Tea", "Bergamot"],
    heartNotes: ["Jasmine", "Peony", "Lily of the Valley"],
    baseNotes: ["White Musk", "Cedarwood", "Vanilla"],
    longevity: "4-6 hours",
    projection: "Moderate",
    occasion: ["Daily Wear", "Office", "Brunch"],
    season: ["Spring", "Summer"],
    concentration: "Eau De Toilette",
    bottleSize: "75ml",
    gender: "Women",
  },
  {
    id: "p003",
    name: "Orbit Oud Intense",
    slug: "orbit-oud-intense",
    brand: "Buy On Earth",
    category: "Perfume",
    subcategory: "Eau De Parfum",
    description: "An intense, smoky oud-based fragrance for the bold and confident.",
    longDescription: "Orbit Oud Intense is for those who make a statement. Rich oud wood, smoky incense, and dark leather create a powerful trail. Finished with hints of vanilla and black amber for depth.",
    price: 4999,
    currency: "INR",
    images: ["https://images.unsplash.com/photo-1608528577891-eb055944f2e7?w=600&q=80", "https://images.unsplash.com/photo-1594035910387-fea081ae7256?w=600&q=80"],
    hoverImage: "https://images.unsplash.com/photo-1594035910387-fea081ae7256?w=600&q=80",
    sizes: [],
    colors: [],
    stock: 40,
    rating: 4.8,
    reviewCount: 156,
    badges: ["Premium", "Limited Drop"],
    tags: ["oud", "intense", "smoky", "luxury"],
    seoTitle: "Orbit Oud Intense | Buy On Earth",
    seoDescription: "Intense smoky oud fragrance. Bold, powerful, unforgettable.",
    isFeatured: true,
    isNewArrival: false,
    isBestSeller: true,
    collection: "signature-scents",
    fragranceFamily: "Woody Oriental",
    topNotes: ["Black Pepper", "Saffron"],
    heartNotes: ["Oud Wood", "Incense", "Dark Rose"],
    baseNotes: ["Leather", "Black Amber", "Vanilla"],
    longevity: "10-12 hours",
    projection: "Beast Mode",
    occasion: ["Evening", "Special Events", "Winter Nights"],
    season: ["Fall", "Winter"],
    concentration: "Eau De Parfum Intense",
    bottleSize: "100ml",
    gender: "Men",
  },
]

// ==================== COLLECTIONS ====================
export const collections: Collection[] = [
  {
    id: "col001",
    name: "Earth Essentials",
    slug: "earth-essentials",
    description: "Everyday wardrobe staples crafted from premium fabrics. T-shirts, joggers, and loungewear you'll reach for daily.",
    image: `${S}/M11596A1_jpg.jpg`,
    productCount: 24
  },
  {
    id: "col002",
    name: "Premium Edit",
    slug: "premium-edit",
    description: "Elevated pieces for those who appreciate fine craftsmanship. Woven shirts, structured dresses, and premium knits.",
    image: `${S}/W13485A3.jpg`,
    productCount: 18
  },
  {
    id: "col003",
    name: "Signature Scents",
    slug: "signature-scents",
    description: "Our curated collection of fragrances. From fresh daytime florals to bold evening ouds.",
    image: "https://images.unsplash.com/photo-1541643600914-78b084683702?w=800&q=80",
    productCount: 6
  },
  {
    id: "col004",
    name: "Summer Resort",
    slug: "summer-resort",
    description: "Vacation-ready pieces. Breezy shirts, lightweight shorts, and effortless dresses.",
    image: `${S}/M11553Bs1.jpg`,
    productCount: 12
  },
  {
    id: "col005",
    name: "Kids' Corner",
    slug: "kids-corner",
    description: "Playful, comfortable, and durable clothing for little ones. Organic cotton, fun prints, and easy-care fabrics.",
    image: `${S}/G22172A1.jpg`,
    productCount: 20
  },
  {
    id: "col006",
    name: "Athleisure Edit",
    slug: "athleisure-edit",
    description: "Performance meets style. Joggers, shorts, and activewear for the modern lifestyle.",
    image: `${S}/M11557A1_jpg.jpg`,
    productCount: 15
  }
]

// ==================== BLOG POSTS ====================
export const blogPosts: BlogPost[] = [
  {
    id: "b001",
    title: "How to Build a Premium Capsule Wardrobe",
    slug: "how-to-build-premium-capsule-wardrobe",
    excerpt: "A capsule wardrobe is the foundation of effortless style. Learn how to build yours with premium essentials.",
    content: "Creating a capsule wardrobe is about investing in quality pieces that work together seamlessly...",
    category: "Men's Style",
    author: "Earth Editorial Team",
    publishDate: "2026-04-15",
    image: `${S}/M11587A_2_jpg.jpg`,
    tags: ["capsule wardrobe", "men's style", "premium fashion"],
    readTime: 8
  },
  {
    id: "b002",
    title: "Best Perfumes for Evening Wear",
    slug: "best-perfumes-for-evening-wear",
    excerpt: "The right fragrance completes any evening look. Discover our curated selection of evening perfumes.",
    content: "Evening fragrances are all about depth, mystery, and lasting power...",
    category: "Perfume Guide",
    author: "Earth Editorial Team",
    publishDate: "2026-04-10",
    image: "https://images.unsplash.com/photo-1541643600914-78b084683702?w=800&q=80",
    tags: ["perfume", "evening wear", "fragrance guide"],
    readTime: 6
  },
  {
    id: "b003",
    title: "Summer Resort Dressing: The Complete Guide",
    slug: "summer-resort-dressing-guide",
    excerpt: "From beach to bar — how to dress for your summer getaway with effortless style.",
    content: "Summer resort dressing is about finding the perfect balance between relaxed and refined...",
    category: "Style Guide",
    author: "Earth Editorial Team",
    publishDate: "2026-04-05",
    image: `${S}/M11553Bs1.jpg`,
    tags: ["summer", "resort wear", "vacation style"],
    readTime: 10
  }
]

// ==================== TESTIMONIALS ====================
export const testimonials = [
  {
    id: "t001",
    name: "Arjun Mehta",
    location: "Mumbai",
    rating: 5,
    review: "The French Terry Oversized Tee is the best quality I've found at this price. Heavyweight feel, perfect oversized fit — exactly what I wanted.",
    product: "French Terry Oversized Tee",
    avatar: "https://images.unsplash.com/photo-1472099645785-5658abf4ff4e?w=100&q=80"
  },
  {
    id: "t002",
    name: "Priya Sharma",
    location: "Delhi",
    rating: 5,
    review: "The Lace Button-Down Shirt is stunning. The embroidery detail is beautiful and the fit is perfect. I get compliments every time I wear it.",
    product: "Lace Button-Down Shirt",
    avatar: "https://images.unsplash.com/photo-1487412720507-e7ab37603c6f?w=100&q=80"
  },
  {
    id: "t003",
    name: "Rohan Krishnan",
    location: "Bangalore",
    rating: 5,
    review: "Earth Noir has incredible longevity — still strong after 10 hours. Worth every rupee. The packaging is also stunning.",
    product: "Earth Noir Eau De Parfum",
    avatar: "https://images.unsplash.com/photo-1500648767791-00dcc994a43e?w=100&q=80"
  },
  {
    id: "t004",
    name: "Kavya Reddy",
    location: "Hyderabad",
    rating: 5,
    review: "My daughter loves the Printed Pyjama Sets! So soft and the prints are adorable. Already ordered two more sets. Great quality for kids.",
    product: "Girls Printed Pyjama Sets",
    avatar: "https://images.unsplash.com/photo-1438761681033-6461ffad8d80?w=100&q=80"
  }
]

// ==================== DATA ACCESS FUNCTIONS ====================
export const getProductsByCategory = (category: ProductCategory): Product[] => {
  return products.filter(p => p.category === category)
}

export const getFeaturedProducts = (): Product[] => {
  return products.filter(p => p.isFeatured)
}

export const getNewArrivals = (): Product[] => {
  return products.filter(p => p.isNewArrival)
}

export const getBestSellers = (): Product[] => {
  return products.filter(p => p.isBestSeller)
}

export const getProductBySlug = (slug: string): Product | undefined => {
  return products.find(p => p.slug === slug)
}

export const getProductsByCollection = (collection: string): Product[] => {
  return products.filter(p => p.collection === collection)
}

export const getRelatedProducts = (product: Product, limit: number = 4): Product[] => {
  return products
    .filter(p => p.id !== product.id && (p.category === product.category || p.subcategory === product.subcategory))
    .slice(0, limit)
}
